apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: config-default
  #namespace: testing
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: config-secret