apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ .Release.Name }}-ingress
  name: {{ .Release.Name }}-ingress
spec:
  rules:
  - host: jenkins-{{ .Values.ingress.environment }}.{{ .Values.ingress.domain }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}-svc
          servicePort: {{ .Values.service.ports.master }}