apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: master
      port: {{ .Values.service.ports.master }}
      targetPort: {{ .Values.service.targetPorts.master }}
    - name: slave
      port: {{ .Values.service.ports.slave }}
      targetPort: {{ .Values.service.targetPorts.slave }}
  selector:
    app: {{ .Release.Name }}-statefulset